# Written by ozipoetra // mitsu00
name: Build Tester

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  WDIR: ${{github.workspace}}
jobs:
  slim_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- uses: rokibhasansagar/slimhub_actions@main
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 4096
          remove-dotnet: 'true'
          remove-docker-images: 'false'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      - name: Free Space After Clearing
        run: |
          cd $WDIR
          echo "Free space:"
          df -h
          echo "Current Directory"
          pwd
          ls
  build:
    needs: slim_build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/sushrut1101/docker:arch
      options:
        --user 1001:1001
        -v "${{github.workspace}}":"${{github.workspace}}"
    steps:
      - uses: actions/checkout@v3
      # Downloading Tools
      - name: Prepare Repo
        run: |
          #cd $WDIR
          cd ~
          mkdir ~/.bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+x ~/.bin/repo
          echo "export PATH=~/bin:$PATH" >> ~/.bashrc
      # Sync Repo (You Can Edit This!)
      - name: Sync Repo
        run: |
          cd $WDIR
          repo init --depth=1 --no-repo-verify -u https://github.com/alphadroid-project/manifest -b alpha-13 --git-lfs -g default,-mips,-darwin,-notdefault
          git clone https://github.com/mitsu00/local_manifest.git --depth 1 -b alpha .repo/local_manifests
          repo sync -c --no-clone-bundle --optimized-fetch --prune --force-sync --fail-fast -j$(nproc --all)
      # Build Test (You Can Edit This!)
      - name: Build Test
        run: |
          cd $WDIR
          . build/envsetup.sh
          export WITH_GMS=0
          export ALLOW_MISSING_DEPENDENCIES=true
          export BUILD_USERNAME=ozipoetra
          export BUILD_HOSTNAME=ozip.my.id
          export TZ=Asia/Jakarta
          lunch lineage_merlinx-user
          mka sepolicy
          mka bootimage
          mka init
